<?php
/**
 * Dependency manifest for the block editor script.
 *
 * Normally generated by @wordpress/scripts. This plugin ships without a build
 * step, so the list is maintained by hand — keep it in sync with the globals
 * index.js actually reads.
 *
 * @package LeadForms
 */

return array(
	'dependencies' => array(
		'wp-blocks',
		'wp-block-editor',
		'wp-components',
		'wp-element',
		'wp-i18n',
		'wp-server-side-render',
	),
	'version'      => '1.0.0',
);
